[theme]
primaryColor = "#C97A9E"
backgroundColor = "#F7F7FB"          # 👈 ESTE ES EL FONDO REAL
secondaryBackgroundColor = "#F6F8F7"
textColor = "#2C3333"
font = "serif"

[client]
showSidebarNavigation = false
