[theme]
# Tonos femeninos/profesionales (rosa + neutrales sobrios)
primaryColor = "#d46a92"          # rosa elegante
backgroundColor = "#ffffff"       # blanco limpio
secondaryBackgroundColor = "#f8f0f4"  # rosa muy claro (suave)
textColor = "#2c2c34"             # gris oscuro profesional
font = "serif"                    # serif da un toque más editorial/profesional

[client]
showSidebarNavigation = false
